"""Add pathways and analytics

Revision ID: 861d9b35213a
Revises: f6c33cce5316
Create Date: 2025-11-21 14:26:19.382094

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '861d9b35213a'
down_revision = 'f6c33cce5316'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pathway_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('order', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.drop_column('reflection_prompt')
        batch_op.drop_column('quiz_data')
        batch_op.drop_column('position')

    with op.batch_alter_table('pathway_progress', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_completed', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('completed_at', sa.DateTime(), nullable=True))
        batch_op.drop_column('completed')
        batch_op.drop_column('completion_date')
        batch_op.drop_column('current_item_id')

    with op.batch_alter_table('pathways', schema=None) as batch_op:
        batch_op.add_column(sa.Column('duration', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('points_reward', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=True))
        batch_op.alter_column('category',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=100),
               existing_nullable=True)
        batch_op.alter_column('difficulty',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=50),
               existing_nullable=True)
        batch_op.drop_constraint(batch_op.f('pathways_creator_id_fkey'), type_='foreignkey')
        batch_op.drop_column('thumbnail_url')
        batch_op.drop_column('published')
        batch_op.drop_column('creator_id')
        batch_op.drop_column('estimated_duration')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pathways', schema=None) as batch_op:
        batch_op.add_column(sa.Column('estimated_duration', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('creator_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('published', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('thumbnail_url', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
        batch_op.create_foreign_key(batch_op.f('pathways_creator_id_fkey'), 'users', ['creator_id'], ['id'])
        batch_op.alter_column('difficulty',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)
        batch_op.alter_column('category',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
        batch_op.drop_column('is_active')
        batch_op.drop_column('points_reward')
        batch_op.drop_column('duration')

    with op.batch_alter_table('pathway_progress', schema=None) as batch_op:
        batch_op.add_column(sa.Column('current_item_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('completion_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('completed', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.drop_column('completed_at')
        batch_op.drop_column('is_completed')

    with op.batch_alter_table('pathway_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('position', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('quiz_data', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('reflection_prompt', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.drop_column('created_at')
        batch_op.drop_column('order')

    # ### end Alembic commands ###
